"""List of server side functions"""

ALL_PMIDS = 'all_pmids'
BEL_BY_ANNOTATION = 'bel_by_annotation'
BEL_BY_LAST_AUTHOR = 'bel_by_last_author'
BEL_BY_PMID = 'bel_by_pmid'
BEL_BY_SUBGRAPH = 'bel_by_subgraph'
BEL_CAUSAL_CORRELATIVE_BY_GENE = 'bel_causal_correlative_by_gene'
BEL_PATH = 'bel_path'
BEL_STATISTICS_EDGES = 'bel_statistics_edges'
BEL_STATISTICS_LAST_AUTHOR_BY_NUMBER_OF_PUBLICATIONS = 'bel_statistics_last_author_by_number_of_publications'
BEL_STATISTICS_LAST_AUTHOR_BY_NUMBER_OF_STATEMENTS = 'bel_statistics_last_author_by_number_of_statements'
BEL_STATISTICS_NAMESPACE_COUNT = 'bel_statistics_namespace_count'
BEL_STATISTICS_NODE_NAMESPACE_ORDER_BY_COUNT = 'bel_statistics_node_namespace_order_by_count'
BEL_STATISTICS_NODE_NAMESPACE_ORDER_BY_NAMESPACE = 'bel_statistics_node_namespace_order_by_namespace'
BEL_STATISTICS_NODES = 'bel_statistics_nodes'
BEL_STATISTICS_PUBLICATION_BY_NUMBER_OF_STATEMENTS = 'bel_statistics_publication_by_number_of_statements'
BEL_STATISTICS_PUBLICATION_BY_YEAR = 'bel_statistics_publication_by_year'
BEL_STATISTICS_SUBGRAPH = 'bel_statistics_subgraph'
BEL_STATISTICS_SUMMARIZE = 'bel_statistics_summarize'
BEL_STATISTICS_TOTAL_BEL_NODES = 'bel_statistics_total_bel_nodes'
BEL_STATISTICS_TOTAL_PUBLICATIONS = 'bel_statistics_total_publications'
BEL_STATISTICS_TOTAL_STATEMENTS = 'bel_statistics_total_stmts'
BELISH = 'belish_helper'
DIRECT_SQL = 'direct_sql'
